services:
  db:
    image: postgres
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: agenda_telefonica
    ports:
      - '5432:5432'